config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  root "posts#index"
  resources :posts
  get "/profile/:id", to: "users#profile"
  # resources :users, only: [:show]  
  # if using show.html.erb inside users folder
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :picture
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise    :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
  has_many  :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    
    def new
		@post = Post.new
	end
    
    def create
       post = Post.new(post_params)
       post.user_id = current_user.id
       post.save
       
       redirect_to "/"
    end
    
    def show
       @posts = Post.find(params[:id]) 
    end
    
    def destroy
        post = Post.find(params[:id])
        post.delete unless post.user_id != current_user.id
        
        redirect_to "/"
    end
    
    def edit
         @post = Post.find(params[:id])
    end
    
    def update
        post = Post.find(params[:id])
        post.update(post_params) unless post.user_id != current_user.id
         
         redirect_to "/posts/#{post.id}"
     end

    private
	def post_params
		params.require(:post).permit(:caption, :picture)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile
        @user = User.find(params[:id])
        @posts = @user.posts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakeinsta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
<p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
</p>
    <ul class="nav">
      <li class="active"><%= link_to "New Post", new_post_path %></li>
    </ul>
    
    <%= yield %>
    
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>

<%=form_for @post do |f| %>
    <div>
    	<label>New description:</label>
    	<%= f.text_area :caption %>
    	<label>Attach Another picture</label>
    	<%= f.file_field :picture%>
    </div>

	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>List of All Posts</h1>

<% @posts.each do |p| %>
    <div>
        <br><%= link_to(p.user.email, "/profile/#{p.user_id}") %></br>
    <% if p.picture.attached? %>
    	<%= image_tag p.picture, height: 200 %>
    <% end %>
        <li><%=link_to p.caption, "posts/#{p.id}" %></li>
    </div>    
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
    <div>
    	<label>Description:</label>
    	<%= f.text_area :caption %>
    	<label>Attach picture</label>
    	<%= f.file_field :picture%>
    </div>

	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%=link_to "HOME", root_path %>
<h1>Post insta</h1>

<% if @posts.picture.attached? %>
    	<%= image_tag @posts.picture, height: 300 %>
<% end %>

<div><%= @posts.caption %></div>

    <% if @posts.user_id == current_user.id %>
        <%=link_to "delete", post_path(@posts),
                             method: :delete,
                             data: {confirm: "Are you sure?"} %>
                            
        <%=link_to "edit", edit_post_path%>                    
        
        <% else %>

    <% end %>                     

                     

app/views/users/profile.html.erb
<%=link_to "HOME", root_path %>
<h2><%= @user.email %></h2>

<% @user.posts.each do |post| %>
    <div>
        <%= image_tag post.picture, height: 200 %>
        <li><%= post.caption %></li>
    </div>    
<% end %>